### ISSUE TITLE
authentication module

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_webservices#14]
In Phylotastic server side, Abu has to create module to obtain access_token that is submitted from mobile app ( and portal so far). And then this module be able to check valid or in-valid access_token with Google to make sure that signed in Google account on app (and portal so far) has enough privileges to access Phylotastic Web Services. If Yes, Phylotastic server will return data, If NO, an exception will be returned.

**Comment by arlin** [comment]
@abusalehmdtayeen, can you clarify the progress on this?  Is it done?   How do we test?

**Comment by abusalehmdtayeen** [comment]
I have finished writing the module to test the validity of access_token. But I have not integrated the module with the services yet because some issues came up when Thanh, Dr. Pontelli and I were discussing the authentication today. We would like to discuss these issues in tomorrow's meeting before I integrate the module with the services.

**Comment by abusalehmdtayeen** [comment]
Authentication module has been integrated with species list services to allow only verified users to access their private lists.

**Comment by arlin** [comment]
so how do we test this?

**Comment by abusalehmdtayeen** [comment]
@arlin : It is now integrated with the species list services. You have to test this feature through Van's web-portal since user can not generate access_token by himself.
