### ISSUE TITLE
do not require sign-in for all content

### ISSUE THREAD

**Issue by kcranston** [phylotastic/phylo_webservices#25]
I was testing the tree search at http://phylo.cs.nmsu.edu:3000/ . It is a big turnoff to have to sign in to do _anything_ on the site. Would be better to let people search / explore the site and then require sign in when required (e.g. for saving / other services).

**Comment by arlin** [comment]
Agreed.   We should think about how to implement this before we get too deep into it.  Part of the rationale is that we want users of phylotastic tools to be able to maintain an identity across clients, so that they can access their content from multiple clients, via a tree gallery and a list server.  The list server will store any taxon lists that you make, with your identity.  This will allow you to access them from multiple clients, e.g., capture a list using the mobile app, then play with it in the web portal.  The gallery will store all your trees, privately by default, but you can also make them public.  The list server currently exists and is only used by the web portal.
