### ISSUE TITLE
plan to implement common-names service

### ISSUE THREAD

**Issue by arlin** [phylotastic/phylo_webservices#54]
An important 1st-quarter project goal is to improve our coverage of high-priority use-cases. 
 For educational use-cases, support for common names is important.

First, explore options for a common name service: 
* ask @dimus about GN resources
* ask @hyanwong about OneZoom resources
* consider using NCBI taxonomy (downloadable SQL dump) with common names

Second, make a plan.  Third, make tickets for implementation.

**Comment by hyanwong** [comment]
Do you want common names in multiple languages?

**Comment by hyanwong** [comment]
If you can map to EoL identifiers you can get common names easily. Or I can throw together a quick OneZoom API to return preferred common names in language X (culled from EoL) for any number of OTT identifiers.

**Comment by hyanwong** [comment]
What would be mutually beneficial would be if any mistakes you spot could be corrected at source in EoL. One issue is that they are desperately trying to roll out version 3 of their site, and I'm not sure how much of a priority the common names correction interface is. I can ask...

**Comment by abusalehmdtayeen** [comment]
Completed common name service for sources NCBI, ITIS and TROPICOS. Looking for other sources to create alternative web service.

**Comment by hyanwong** [comment]
@abusalehmdtayeen do you want to use the OneZoom common names API. You can try it by e.g. http://beta.onezoom.org/API/otts2vns.json?otts=770315,3597016,178482,872567 which gives common names for Open Tree Taxonomy identifiers in the default browser language, or http://beta.onezoom.org/API/otts2vns.json?otts=770315,3597016,178482,872567&lang=en to force english, or http://beta.onezoom.org/API/otts2vns.json?otts=770315,3597016,178482,872567&lang=ar for arabic, 'zh' for chinese, etc. We will soon be changing the API so that it also returns the lang used in an extra "'lang':'en-us'" type item.

There are 145985 Open Tree ids in our DB which have common names. Many have multiple versions, and you can get all these by appending `&all=1`, e.g.

http://beta.onezoom.org/API/otts2vns.json?otts=770315,3597016,178482,872567&all=1

(try it!)
