### ISSUE TITLE
work on pruning service

### ISSUE THREAD

**Issue by thanhnh-infinity** [phylotastic/phylo_webservices#7]

**Comment by thanhnh-infinity** [comment]
Find service to reduce huge tree (Pruning service)
There are 2 ways be able to follow
- Given a list of species names => Pruning => uses Open Tree => Get tree
- or Given a list of species names => uses Open Tree => get huge tree => pruning service => Get correct tree

**Comment by thanhnh-infinity** [comment]
Try to find a good web service OR desktop software for this task

**Comment by arlin** [comment]
I think we need to talk about this.  A pruning service should have a cache.   OpenTree is not updated very often. They only come out with new versions every few months.  

In generally, all Phylotastic data providers should advertise the version number of their data, so that clients will know when to update their cached version.

**Comment by arlin** [comment]
As discussed today, we want to use induced_subtree instead of this.  I created a separate ticket for that.  This can't be moved to back-log or tagged with wontfix

**Comment by thanhnh-infinity** [comment]
I will tag this ticket with wontfix

**Comment by arlin** [comment]
ok, will move this to done.
